server:
  port: 8050
spring:
  datasource:
    databaseName: shop
    portNumber: 5432
    serverName: localhost
    driverClassName: "org.postgresql.Driver"
    jdbcUrl: "jdbc:postgresql://127.0.0.1/shop"
    username: postgres
    password: "superpass"
    minimumIdle: 10
    maximumPoolSize: 20
    idleTimeout: 180000
    initializationFailFast: true
    maxLifetime: 1800000
    type: com.zaxxer.hikari.HikariDataSource
jwt:
  web_origin: http://localhost:4200/