-- the password hash is generated by BCrypt Calculator Generator(https://www.dailycred.com/article/bcrypt-calculator)
INSERT INTO core.users(id, password, first_name, last_name, email, phone_number, enabled) VALUES
  (1, '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Александр', 'Иванов', 'user@tiksoft.com', '+996772136130', true);
INSERT INTO core.users(id, password, first_name, last_name, email, phone_number, enabled) VALUES
  (2, '$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra', 'Роман', 'Александров', 'admin@tiksoft.com', '+996557136130', true);

INSERT INTO core.authority(id, name) VALUES (1, 'ROLE_USER');
INSERT INTO core.authority(id, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO core.user_authority(user_id, authority_id) VALUES (1, 1);
INSERT INTO core.user_authority(user_id, authority_id) VALUES (2, 1);
INSERT INTO core.user_authority(user_id, authority_id) VALUES (2, 2);