spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
app:
  name: Shop
jwt:
  header: Authorization
  expires_in: 3000 # 50 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: queenvictoria